angle_threshold: 15.0
default_workers: 10
dssr_dir: data/json_dssr
exemplar_templates_dir: basepair-exemplars
idealized_templates_dir: basepair-idealized
legacy_json_dir: data/json_legacy
max_hbond_distance: 3.5
min_hbond_distance: 2.4
modern_json_dir: data/json
n1n9_range: !!python/tuple
- 8.0
- 9.5
output_dir: results
pdb_dir: data/pdb
rmsd_threshold: 1.5
slot_hbonds_dir: data/json/slot_hbonds
verbose: false
viz_output_dir: viz_output
